### ISSUE TITLE
Sanic 20.3.0: TypeError: 'Request' object does not support item assignment

### ISSUE THREAD

**Issue by mikekeda** [pyx/sanic-wtf#17]
Sanic 20.3.0 doesn't support item assignment.

lines like `request['session'] = session` should be replaced with `request.ctx.session = session`

**Comment by SharpBit** [comment]
Since this project is dead I guess i'm going to have to do `pip install git+https://github.com/mikekeda/sanic-wtf` instead and i recommend anyone else having this issue to do the same

**Comment by SpootDev** [comment]
Yeah, looks that way, thanks @mikekeda for your branch.

**Comment by pyx** [comment]
Sorry about the hiatus.
Thanks for the patch, I will merge it and make a new release shortly.

BTW, @mikekeda are you still using this? If you are interested, I will put you into collaborators list.

**Comment by mikekeda** [comment]
@pyx Yeah, I'm using this, and I would like to join collaborators list

**Comment by pyx** [comment]
@mikekeda invitation sent. Thank you for your help. Cloud you please merge your patch? Then I will make a new release. Remember add your name in AUTHORS. Thank you.

**Comment by mikekeda** [comment]
merged

**Comment by pyx** [comment]
Thanks.
