### ISSUE TITLE
Possible race condition?

### ISSUE THREAD

**Issue by pyx** [pyx/sanic-wtf#6]
Since it is not just me using it now, I leave this here, just for the record, and for publicity.

Like I said in the source code, the current mechanism the CSRF works is because there is a registered middleware to change `Form.Meta.csrf_context` to the current request session at the beginning of request handling, and because of the thread-sharing nature of async style, I can think of the possibility of an `await` or `yield from` happened before the `form.validate()` call, will that change the session? I still did not wrap my head around about that...

I have this weird design due to avoidance of explicitly passing in the current request object each time we use the form, is it really a good idea?

Comments, suggestions, criticisms are welcome.

**Comment by pyx** [comment]
I think I have a better idea here, instead of passing in `request.form`, we require the whole `request` object, then it will be set as `self.request`, in the case that request is not provided, the form will disable CSRF validation upon initialization.

Pros:
- listener and middleware no longer needed, saves CPU cycles
- await/yield from safe
- `request` not long required in any other method, like the possible `validate_on_submit() -> bool`
- no dark magic in implementation

Cons:
- different API than Flask-WTF

I think I will go for it, probably later today or tomorrow if no PR by then ;D

**Comment by lixxu** [comment]
agreed on keep `self.request`.

**Comment by pyx** [comment]
Update:
I am working on it with my spare time.
