### ISSUE TITLE
Access CSRF token in js

### ISSUE THREAD

**Issue by hashgupta** [pyx/sanic-wtf#8]
I need to access the CSRF token in the client side is so I could use a rest API to use the website. It would be helpful to be able to access the CSRF in the request handler just like you can in flask-wtforms

**Comment by pyx** [comment]
Will you show me how you want it to work?

Remember that the csrf_token is accessible via `form.csrf_token.current_token`, according to the source code of WTForms.

So, this
```python
return response.json({'csrf_token': form.csrf_token.current_token})
```
might be just what you want.

**Comment by hashgupta** [comment]
Thanks
